### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by vgaggia** [suurjaak/InputScope#24]
Hey, i'm getting the error:
.NET�������������System.Runtime.Remoting.RemotingException: Tcp channel protocol violation: expecting preamble.
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpServerSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpServerTransportSink.ServiceRequest(Object state)
   at System.Runtime.Remoting.Channels.SocketHandler.ProcessRequestNow()����

**Comment by suurjaak** [comment]
That is a strange error indeed.. Where are you seeing this?

**Comment by vgaggia** [comment]
When i click Open Statistics, it just displays in the browser

**Comment by suurjaak** [comment]
Can you provide a screenshot?

**Comment by vgaggia** [comment]
Sure, here you go
<img width="533" alt="Screenshot" src="https://user-images.githubusercontent.com/1644490/223053728-530396ac-9518-4e92-ad17-edeeeea8bb59.png">

**Comment by suurjaak** [comment]
What is the result if you shut down InputScope and refresh the browser page of http://localhost:8099 ?

**Comment by vgaggia** [comment]
Ohh yeah its something else causing it, can i change the port?

**Comment by vgaggia** [comment]
I figured out how to change the port, not sure what that is running on that port on my pc i'll have to figure that out, thanks for the help!
